/// Flutter icons NavBarIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavBarIcons
///      fonts:
///       - asset: fonts/NavBarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NavBarIcons {
  NavBarIcons._();

  static const _kFontFam = 'NavBarIcons';
  static const String? _kFontPkg = null;

  static const IconData blog = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
